name: Action Checking
on:
  push:
    branches: ["main"]
jobs:
  first_demo_job:
    runs-on: ubuntu-latest
    name: The first demo job
    steps:
      - name: Show the demo running
        run: |
          echo Hello World
